
.PHONY:clean
mymain:main.o max.o min.o
	gcc -g main.o max.o min.o -o mymain
main.o:main.c
	gcc -o main.o -c main.c
max.o:max.c
	gcc -o max.o -c max.c
min.o:min.c
	gcc -o min.o -c min.c
clean:
	rm -rf min.o max.o main.o mymain